[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'omicspylib'
version = '0.2.0'
description = 'A python library for omics data analysis'
readme = 'README.md'
authors = [
    { name = 'Kostas Tsolis', email = 'kostas.tsolis@dialectos.ai' }
]
license = { file = 'LICENSE' }
requires-python = '>=3.10'
dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.0.0",
    "scipy>=1.13.1",
    "statsmodels>=0.14.0",
    "matplotlib>=3.0.1",
    "matplotlib-venn>=0.11.1",
    "seaborn>=0.11.1",
    "scikit-learn>=1.0.0",
    "requests>=2.0.0",
    "typing-extensions>=4.16.0",
    "ipykernel>=7.3.0",
]

[project.urls]
homepage = 'https://github.com/dialectos-ai/omicspylib'
documentation = 'https://omicspylib.readthedocs.io/en/latest/index.html'
repository = 'https://github.com/dialectos-ai/omicspylib'

[dependency-groups]
dev = [
    "pytest",
    "mypy",
    "pylint",
    "ruff",
    "sphinx",
    "sphinx-rtd-theme",
    "nbsphinx",
    "types-scipy-sparse",
    "types-requests",
    "pyright>=1.1.411",
    "pandas-stubs~=2.3.3",
    "scipy-stubs>=1.15.3.0",
    "pydata-sphinx-theme>=0.19.0",
]


[tool.pyright]
# Replace '.venv' with the name of your virtual environment folder
venvPath = "."
venv = ".venv"
